version: "3.9"
services:
  leaderboard_worker:
    build: ./leaderboard-worker
  server:
    build: ./server
    ports:
      - "8080:80" # Only expose the HTTP API
  discord_bot:
    build: ./discord-bot
    ports:
      - "3000:3000"
  postgres:
    image: "postgres:15.1-alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=airdog
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
